### ISSUE TITLE
Unexpected token '.' When using Node 12. 

### ISSUE THREAD

**Issue by markstos** [phhu/aws-secrets-to-env#2] opened 2021-09-30 15:57 UTC
This module appears to be just what I want, but generated an unclear error when I tried it:

```
aws-secrets-to-env --accessKeyId=REDACTED --secretAccessKey=REDACTED --secretid=/project/laptop --region=us-east-1
Unexpected token '.'
````

Maybe I've done something wrong, but the error handling could be improved.

**Comment by markstos** [comment] 2021-09-30 16:03
On a hunch, I tried upgrading my Node.js from 12 to 16 then I got normal output ( Access Denied, but it was a  clear error). 

It would be great if Node 12 could be supported since it's still an actively support LTS release. Either way, `package.json` should be updated with an `engines` section that declares the minimum Node version you support.

**Comment by phhu** [comment] 2021-09-30 17:44
This was caused by my having used `?.` (optional changing operator -https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). I've fixed by substituting with `x && x.y`. I tested and the script seems to works on node >= 8 now, as per the new engines field.

Please try v0.0.18 and let me know if it works.

**Comment by markstos** [comment] 2021-09-30 18:10
Thanks!

**Comment by markstos** [comment] 2021-09-30 18:15
I have confirmed this works with Node.js 12.22.6.

**Comment by markstos** [comment] 2021-09-30 18:16
I also confirmed it works with Node 8.

**Comment by phhu** [comment] 2021-09-30 18:18
Thanks, closing. Let me know if any other issues!

**Closed as completed by phhu** 2021-09-30 18:18 UTC
